name: CI-CD-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install the required packages 
      run: npm install
    - name: Run unit Tests
      run: npm run test:unit
    - name: Dispay SoftUni Username
      run: echo "PetarPaunov"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true
        build-and-test:
    - name: Waits 120sec bofore executing next step
      run: sleep 120
      
  run-ui-tests:

    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install the required packages 
      run: npm install
    - name: Setup playwright
      run: npx playwright install
    - name: Run UI Tests
      run: npm run test:ui